// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr092l74SqrvaRpNxgsXxP2SmM5iTCLjU',
    appId: '1:64533756427:web:3d6afa0ce82c83fb04e50e',
    messagingSenderId: '64533756427',
    projectId: 'chat-meta-a6a42',
    authDomain: 'chat-meta-a6a42.firebaseapp.com',
    storageBucket: 'chat-meta-a6a42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2iAlVXj_aTAjNuKnojoktuJRPAYwhu4w',
    appId: '1:64533756427:android:9ee6c735d575d6c004e50e',
    messagingSenderId: '64533756427',
    projectId: 'chat-meta-a6a42',
    storageBucket: 'chat-meta-a6a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJV3FeIh-_RLZX7RY8ADL2a55P40qZz5k',
    appId: '1:64533756427:ios:9e840159e25164f704e50e',
    messagingSenderId: '64533756427',
    projectId: 'chat-meta-a6a42',
    storageBucket: 'chat-meta-a6a42.appspot.com',
    iosBundleId: 'com.example.chatApplicationIubCse464',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJV3FeIh-_RLZX7RY8ADL2a55P40qZz5k',
    appId: '1:64533756427:ios:9e840159e25164f704e50e',
    messagingSenderId: '64533756427',
    projectId: 'chat-meta-a6a42',
    storageBucket: 'chat-meta-a6a42.appspot.com',
    iosBundleId: 'com.example.chatApplicationIubCse464',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr092l74SqrvaRpNxgsXxP2SmM5iTCLjU',
    appId: '1:64533756427:web:a34a17a17e094e0804e50e',
    messagingSenderId: '64533756427',
    projectId: 'chat-meta-a6a42',
    authDomain: 'chat-meta-a6a42.firebaseapp.com',
    storageBucket: 'chat-meta-a6a42.appspot.com',
  );
}
